version: "3.9"
services:
  db:
    image: postgres:14
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
    ports:
      - "5432:5432"

  api:
    build:
      context: .
      args:
        BUNDLE_DEPLOYMENT: "0"
        RAILS_ENV_ARG: "development"
    user: root
    command: bash -c "cd /rails && bundle check || bundle install && rm -f tmp/pids/server.pid && bundle exec rails s -b '0.0.0.0'"
    volumes:
      - .:/rails
      - bundle_cache:/usr/local/bundle
    ports:
      - "3001:3000"
    depends_on:
      - db
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
      POSTGRES_HOST: db
      RAILS_ENV: development
      SECRET_KEY_BASE: development_secret_dummy_key
      BUNDLE_DEPLOYMENT: "0"
      BUNDLE_FROZEN: "0"

volumes:
  postgres_data:
  bundle_cache: